name: Angular CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install latest Chrome
      run: |
        sudo apt update
        sudo apt --only-upgrade install google-chrome-stable
        google-chrome --version
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Run unit tests
      run: xvfb-run npm test -- --watch=false
